### ISSUE TITLE
provide frontend source code in this repo

### ISSUE THREAD

**Issue by realies** [Akegarasu/lora-scripts#531]

**Comment by Akegarasu** [comment]
The frontend source code is only accessible to a limited number of people. May I understand why you are interested in the frontend source code?

**Comment by realies** [comment]
to improve it, what makes it so unique to only provide a compiled bundle with it?

**Comment by Akegarasu** [comment]
Since I'm unsure of your nationality, let me briefly explain the situation regarding this project in my country (China). Here, some vendors violate project licenses by modifying the code, removing original links, and then selling the compiled project. Therefore, the frontend code is kept closed-source.

**Comment by realies** [comment]
Thanks for explaining the reason behind the decision. But what makes you think the front-end can't be unbundled into a more easy to work with source code relatively easily? Or just text replacing licenses and links from the bundle and reselling it?

I think this decision would not repel people who are determined to do this.
